### ISSUE TITLE
Server attempting to load class GuiScreen; obviously does not exist.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#65]
Since the runtime is on the server side of things, `GuiScreen` is not available.

The fix is to find the line of code accessing `GuiScreen` and make it aware of which `enum Side` it is on.

Important part of the not-given-here crashlog:

```log
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
    at talecraft.TaleCraftItems.init(TaleCraftItems.java:109) ~[TaleCraftItems.class:?]
    at talecraft.TaleCraft.preInit(TaleCraft.java:96) ~[TaleCraft.class:?]
```

Line of code causing this:
https://github.com/tiffit/TaleCraft/blob/78816a3f48c0e7d7d4c428557c5784b5bf45e42b/src/main/java/talecraft/TaleCraftItems.java#L109

Versions that suffer from this:
* `TaleCraft 0.2.19`

**Comment by Longor1996** [comment]
I probably identified the issue. The file `MovingBlockCreator` (an Item) has a client-side import whereas all other items do not have such an import.
